name: Version, Tag and Publish to npm

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensures history is checked out for versioning

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Set to your Node.js version
        registry-url: 'https://registry.npmjs.org/'
      
    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Bump version and tag
      id: bump_version
      uses: phips28/gh-action-bump-version@master
      with:
        tag-prefix: 'v'  # Set this to 'v' if you want your tags like 'v1.0.0'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.bump_version.outputs.new_tag }}
        release_name: Release ${{ steps.bump_version.outputs.new_tag }}
        body: "" # Optional: Add custom body text here if needed
        draft: false
        prerelease: false
        generate_release_notes: true # This enables automatic release note generation

    - name: Setup NPM Authentication
      run: |
        echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
        cat ~/.npmrc
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
    
    - name: Publish to npm
      run: |
        npm config set access public
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

